# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_ImageEditor(object):
    def setupUi(self, ImageEditor):
        if not ImageEditor.objectName():
            ImageEditor.setObjectName(u"ImageEditor")
        ImageEditor.resize(800, 600)
        self.browseButton = QPushButton(ImageEditor)
        self.browseButton.setObjectName(u"browseButton")
        self.browseButton.setGeometry(QRect(560, 30, 100, 32))
        self.imgPath = QLineEdit(ImageEditor)
        self.imgPath.setObjectName(u"imgPath")
        self.imgPath.setGeometry(QRect(171, 30, 370, 30))
        self.tabWidget = QTabWidget(ImageEditor)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(30, 90, 731, 451))
        self.basic = QWidget()
        self.basic.setObjectName(u"basic")
        self.label = QLabel(self.basic)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 161, 20))
        self.comboBox = QComboBox(self.basic)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(180, 20, 151, 32))
        self.label_2 = QLabel(self.basic)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 60, 161, 20))
        self.label_3 = QLabel(self.basic)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(390, 60, 161, 20))
        self.widget_3 = QWidget(self.basic)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(40, 120, 281, 211))
        self.org1 = QLabel(self.widget_3)
        self.org1.setObjectName(u"org1")
        self.org1.setGeometry(QRect(10, 5, 241, 211))
        self.widget_4 = QWidget(self.basic)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(390, 120, 271, 211))
        self.fin1 = QLabel(self.widget_4)
        self.fin1.setObjectName(u"fin1")
        self.fin1.setGeometry(QRect(10, 9, 241, 211))
        self.tabWidget.addTab(self.basic, "")
        self.filter = QWidget()
        self.filter.setObjectName(u"filter")
        self.label_4 = QLabel(self.filter)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 161, 20))
        self.comboBox_2 = QComboBox(self.filter)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(180, 20, 151, 32))
        self.label_7 = QLabel(self.filter)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 70, 161, 20))
        self.label_8 = QLabel(self.filter)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(390, 70, 161, 20))
        self.widget_5 = QWidget(self.filter)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(40, 120, 281, 211))
        self.org2 = QLabel(self.widget_5)
        self.org2.setObjectName(u"org2")
        self.org2.setGeometry(QRect(10, 5, 241, 211))
        self.widget_6 = QWidget(self.filter)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(390, 120, 271, 211))
        self.fin2 = QLabel(self.widget_6)
        self.fin2.setObjectName(u"fin2")
        self.fin2.setGeometry(QRect(10, 9, 241, 211))
        self.tabWidget.addTab(self.filter, "")
        self.morph = QWidget()
        self.morph.setObjectName(u"morph")
        self.label_5 = QLabel(self.morph)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 20, 161, 20))
        self.comboBox_3 = QComboBox(self.morph)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(200, 20, 151, 32))
        self.label_9 = QLabel(self.morph)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 80, 161, 20))
        self.label_10 = QLabel(self.morph)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(390, 80, 161, 20))
        self.widget_7 = QWidget(self.morph)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(50, 120, 281, 211))
        self.org4 = QLabel(self.widget_7)
        self.org4.setObjectName(u"org4")
        self.org4.setGeometry(QRect(10, 5, 241, 211))
        self.widget_8 = QWidget(self.morph)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(400, 120, 271, 211))
        self.fin4 = QLabel(self.widget_8)
        self.fin4.setObjectName(u"fin4")
        self.fin4.setGeometry(QRect(10, 9, 241, 211))
        self.tabWidget.addTab(self.morph, "")
        self.hough = QWidget()
        self.hough.setObjectName(u"hough")
        self.comboBox_4 = QComboBox(self.hough)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(190, 20, 191, 32))
        self.label_6 = QLabel(self.hough)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 20, 161, 20))
        self.label_11 = QLabel(self.hough)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 80, 161, 20))
        self.label_12 = QLabel(self.hough)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(390, 80, 161, 20))
        self.widget = QWidget(self.hough)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 130, 281, 211))
        self.org3 = QLabel(self.widget)
        self.org3.setObjectName(u"org3")
        self.org3.setGeometry(QRect(10, 5, 241, 211))
        self.widget_2 = QWidget(self.hough)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(390, 140, 271, 211))
        self.fin3 = QLabel(self.widget_2)
        self.fin3.setObjectName(u"fin3")
        self.fin3.setGeometry(QRect(10, 9, 241, 211))
        self.tabWidget.addTab(self.hough, "")
        self.label_13 = QLabel(ImageEditor)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(40, 30, 121, 31))

        self.retranslateUi(ImageEditor)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(ImageEditor)
    # setupUi

    def retranslateUi(self, ImageEditor):
        ImageEditor.setWindowTitle(QCoreApplication.translate("ImageEditor", u"ImageEditor", None))
        self.browseButton.setText(QCoreApplication.translate("ImageEditor", u"Browse", None))
        self.label.setText(QCoreApplication.translate("ImageEditor", u"Choisir la transformation", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("ImageEditor", u"Inversement", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("ImageEditor", u"Egalisation", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("ImageEditor", u"Etirement", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("ImageEditor", u"Fct Beta", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("ImageEditor", u"Fct Gamma", None))

        self.label_2.setText(QCoreApplication.translate("ImageEditor", u"Image Originale", None))
        self.label_3.setText(QCoreApplication.translate("ImageEditor", u"Image Finale", None))
        self.org1.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.fin1.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basic), QCoreApplication.translate("ImageEditor", u"Basiques", None))
        self.label_4.setText(QCoreApplication.translate("ImageEditor", u"Choisir un filtre", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("ImageEditor", u"Median", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("ImageEditor", u"Moyenne", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("ImageEditor", u"Sobel", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("ImageEditor", u"Prewitt", None))

        self.label_7.setText(QCoreApplication.translate("ImageEditor", u"Image Originale", None))
        self.label_8.setText(QCoreApplication.translate("ImageEditor", u"Image Finale", None))
        self.org2.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.fin2.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filter), QCoreApplication.translate("ImageEditor", u"Filtrage", None))
        self.label_5.setText(QCoreApplication.translate("ImageEditor", u"Choisir une morphologie", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("ImageEditor", u"Erosion", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("ImageEditor", u"Dilatation", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("ImageEditor", u"Contour", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("ImageEditor", u"Ouverture", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("ImageEditor", u"Fermeture", None))

        self.label_9.setText(QCoreApplication.translate("ImageEditor", u"Image Originale", None))
        self.label_10.setText(QCoreApplication.translate("ImageEditor", u"Image Finale", None))
        self.org4.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.fin4.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.morph), QCoreApplication.translate("ImageEditor", u"Morphologie", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("ImageEditor", u"Detection des droites", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("ImageEditor", u"Detection des cercles", None))

        self.label_6.setText(QCoreApplication.translate("ImageEditor", u"Choisir un type", None))
        self.label_11.setText(QCoreApplication.translate("ImageEditor", u"Image Originale", None))
        self.label_12.setText(QCoreApplication.translate("ImageEditor", u"Image Finale", None))
        self.org3.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.fin3.setText(QCoreApplication.translate("ImageEditor", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hough), QCoreApplication.translate("ImageEditor", u"Hough", None))
        self.label_13.setText(QCoreApplication.translate("ImageEditor", u"Charger une image", None))
    # retranslateUi

